export const list = [
  { key: 'mces', name: '臺北市松山區民族國民小學', abbr: '民族國小' },
  { key: 'jaes', name: '臺北市大安區建安國民小學', abbr: '建安國小' },
  { key: 'tyes', name: '臺北市萬華區東園國民小學', abbr: '東園國小' },
  { key: 'wjhs', name: '臺北市立五常國民中學', abbr: '五常國中' },
  { key: 'ktjg', name: '臺北市立古亭國民中學', abbr: '古亭國中' },
  { key: 'blsh', name: '臺北市立百齡高級中學(國中部)', abbr: '百齡高中' },
  { key: 'jjhs', name: '臺北市立金華國民中學', abbr: '金華國中' },
  { key: 'zzsh', name: '臺北市立中正高級中學', abbr: '中正高中' },
  { key: 'mlsh', name: '臺北市立明倫高級中學', abbr: '明倫高中' },
  { key: 'fhsh', name: '臺北市立復興高級中學', abbr: '復興高中' },
]

export const detail = {
  mces: [
    { id: 1, title: '作品名稱', content: '作者姓名' },
    { id: 2, title: '作品名稱', content: '作者姓名' },
    { id: 3, title: '作品名稱', content: '作者姓名' },
    { id: 4, title: '作品名稱', content: '作者姓名' },
    { id: 5, title: '作品名稱', content: '作者姓名' },
    { id: 6, title: '作品名稱', content: '作者姓名' },
    { id: 7, title: '作品名稱', content: '作者姓名' },
    { id: 8, title: '作品名稱', content: '作者姓名' },
    { id: 9, title: '作品名稱', content: '作者姓名' },
    { id: 10, title: '作品名稱', content: '作者姓名' }
  ],
  jaes: [
    { id: 1, title: '作品名稱', content: '作者姓名' },
    { id: 2, title: '作品名稱', content: '作者姓名' },
    { id: 3, title: '作品名稱', content: '作者姓名' },
    { id: 4, title: '作品名稱', content: '作者姓名' },
    { id: 5, title: '作品名稱', content: '作者姓名' },
    { id: 6, title: '作品名稱', content: '作者姓名' },
    { id: 7, title: '作品名稱', content: '作者姓名' },
    { id: 8, title: '作品名稱', content: '作者姓名' },
    { id: 9, title: '作品名稱', content: '作者姓名' },
    { id: 10, title: '作品名稱', content: '作者姓名' }
  ],
  tyes: [
    { id: 1, title: '作品名稱', content: '作者姓名' },
    { id: 2, title: '作品名稱', content: '作者姓名' },
    { id: 3, title: '作品名稱', content: '作者姓名' },
    { id: 4, title: '作品名稱', content: '作者姓名' },
    { id: 5, title: '作品名稱', content: '作者姓名' },
    { id: 6, title: '作品名稱', content: '作者姓名' },
    { id: 7, title: '作品名稱', content: '作者姓名' },
    { id: 8, title: '作品名稱', content: '作者姓名' },
    { id: 9, title: '作品名稱', content: '作者姓名' },
    { id: 10, title: '作品名稱', content: '作者姓名' }
  ],
  wjhs: [
    { id: 1, title: '作品名稱', content: '作者姓名' },
    { id: 2, title: '作品名稱', content: '作者姓名' },
    { id: 3, title: '作品名稱', content: '作者姓名' },
    { id: 4, title: '作品名稱', content: '作者姓名' },
    { id: 5, title: '作品名稱', content: '作者姓名' },
    { id: 6, title: '作品名稱', content: '作者姓名' },
    { id: 7, title: '作品名稱', content: '作者姓名' },
    { id: 8, title: '作品名稱', content: '作者姓名' },
    { id: 9, title: '作品名稱', content: '作者姓名' },
    { id: 10, title: '作品名稱', content: '作者姓名' }
  ],
  ktjg: [
    { id: 1, title: '作品名稱', content: '作者姓名' },
    { id: 2, title: '作品名稱', content: '作者姓名' },
    { id: 3, title: '作品名稱', content: '作者姓名' },
    { id: 4, title: '作品名稱', content: '作者姓名' },
    { id: 5, title: '作品名稱', content: '作者姓名' },
    { id: 6, title: '作品名稱', content: '作者姓名' },
    { id: 7, title: '作品名稱', content: '作者姓名' },
    { id: 8, title: '作品名稱', content: '作者姓名' },
    { id: 9, title: '作品名稱', content: '作者姓名' },
    { id: 10, title: '作品名稱', content: '作者姓名' }
  ],
  blsh: [
    { id: 1, title: '作品名稱', content: '作者姓名' },
    { id: 2, title: '作品名稱', content: '作者姓名' },
    { id: 3, title: '作品名稱', content: '作者姓名' },
    { id: 4, title: '作品名稱', content: '作者姓名' },
    { id: 5, title: '作品名稱', content: '作者姓名' },
    { id: 6, title: '作品名稱', content: '作者姓名' },
    { id: 7, title: '作品名稱', content: '作者姓名' },
    { id: 8, title: '作品名稱', content: '作者姓名' },
    { id: 9, title: '作品名稱', content: '作者姓名' },
    { id: 10, title: '作品名稱', content: '作者姓名' }
  ],
  jjhs: [
    { id: 1, title: '作品名稱', content: '作者姓名' },
    { id: 2, title: '作品名稱', content: '作者姓名' },
    { id: 3, title: '作品名稱', content: '作者姓名' },
    { id: 4, title: '作品名稱', content: '作者姓名' },
    { id: 5, title: '作品名稱', content: '作者姓名' },
    { id: 6, title: '作品名稱', content: '作者姓名' },
    { id: 7, title: '作品名稱', content: '作者姓名' },
    { id: 8, title: '作品名稱', content: '作者姓名' },
    { id: 9, title: '作品名稱', content: '作者姓名' },
    { id: 10, title: '作品名稱', content: '作者姓名' }
  ],
  zzsh: [
    { id: 1, title: '作品名稱', content: '作者姓名' },
    { id: 2, title: '作品名稱', content: '作者姓名' },
    { id: 3, title: '作品名稱', content: '作者姓名' },
    { id: 4, title: '作品名稱', content: '作者姓名' },
    { id: 5, title: '作品名稱', content: '作者姓名' },
    { id: 6, title: '作品名稱', content: '作者姓名' },
    { id: 7, title: '作品名稱', content: '作者姓名' },
    { id: 8, title: '作品名稱', content: '作者姓名' },
    { id: 9, title: '作品名稱', content: '作者姓名' },
    { id: 10, title: '作品名稱', content: '作者姓名' }
  ],
  mlsh: [
    { id: 1, title: '作品名稱', content: '作者姓名' },
    { id: 2, title: '作品名稱', content: '作者姓名' },
    { id: 3, title: '作品名稱', content: '作者姓名' },
    { id: 4, title: '作品名稱', content: '作者姓名' },
    { id: 5, title: '作品名稱', content: '作者姓名' },
    { id: 6, title: '作品名稱', content: '作者姓名' },
    { id: 7, title: '作品名稱', content: '作者姓名' },
    { id: 8, title: '作品名稱', content: '作者姓名' },
    { id: 9, title: '作品名稱', content: '作者姓名' },
    { id: 10, title: '作品名稱', content: '作者姓名' }
  ],
  fhsh: [
    { id: 1, title: '作品名稱', content: '作者姓名' },
    { id: 2, title: '作品名稱', content: '作者姓名' },
    { id: 3, title: '作品名稱', content: '作者姓名' },
    { id: 4, title: '作品名稱', content: '作者姓名' },
    { id: 5, title: '作品名稱', content: '作者姓名' },
    { id: 6, title: '作品名稱', content: '作者姓名' },
    { id: 7, title: '作品名稱', content: '作者姓名' },
    { id: 8, title: '作品名稱', content: '作者姓名' },
    { id: 9, title: '作品名稱', content: '作者姓名' },
    { id: 10, title: '作品名稱', content: '作者姓名' }
  ]
}
