export const school = [
  { key: 'mces', name: '臺北市松山區民族國民小學', abbr: '民族國小' },
  { key: 'jaes', name: '臺北市大安區建安國民小學', abbr: '建安國小' },
  { key: 'tyes', name: '臺北市萬華區東園國民小學', abbr: '東園國小' },
  { key: 'wjhs', name: '臺北市立五常國民中學', abbr: '五常國中' },
  { key: 'ktjg', name: '臺北市立古亭國民中學', abbr: '古亭國中' },
  { key: 'blsh', name: '臺北市立百齡高級中學(國中部)', abbr: '百齡高中' },
  { key: 'jjhs', name: '臺北市立金華國民中學', abbr: '金華國中' },
  { key: 'zzsh', name: '臺北市立中正高級中學', abbr: '中正高中' },
  { key: 'mlsh', name: '臺北市立明倫高級中學', abbr: '明倫高中' },
  { key: 'fhsh', name: '臺北市立復興高級中學', abbr: '復興高中' },
]

export const article = {
  mces: [
    { id: 1, title: '笑臉餅乾', teacher: '陳映竹', author: '楊少嘉/三年級', tool: '水墨/四開', description: '我想畫笑臉餅乾的原因是因為餅乾排排站看起來很療癒，而且上了金色顏料的餅乾，看起來更美味。' },
    { id: 2, title: '繽紛的海洋之旅', teacher: '陳映竹', author: '仇俠為/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 3, title: '我的夢想', teacher: '陳映竹', author: '蔡岑星/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 4, title: '我的祕密花園', teacher: '陳映竹', author: '陳品云/三年級', tool: '水墨/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 5, title: '理髮記', teacher: '林政榮', author: '林玉騏/四年級', tool: '水墨/ 70 × 34cm', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 6, title: '大人的緊張', teacher: '林政榮', author: '連恩琍/四年級', tool: '彩畫/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 7, title: '海裡的白鯨魚', teacher: '林政榮', author: '陳莆升/四年級', tool: '漫畫/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 8, title: '瘋狂大胃王', teacher: '林政榮', author: '蔡靖瑜/四年級', tool: '設計/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 9, title: '又貪又躁不思考，月底只好去吃草', teacher: '黃致萍', author: '徐開勖/五年級', tool: '漫畫/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 10, title: '愛惜動物', teacher: '黃致萍', author: '陳亞其/五年級', tool: '設計/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 11, title: '臺灣之美', teacher: '黃致萍', author: '楊湘寧/五年級', tool: '漫畫/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 12, title: '心靈', teacher: '黃致萍', author: '陳安璐/五年級', tool: '彩畫/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 13, title: '大稻埕的新與舊', teacher: '戴貝羽', author: '簡愷良/六年級', tool: '彩畫/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 14, title: '石虎的生存危機', teacher: '戴貝羽', author: '張鈊喬/六年級', tool: '漫畫/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 15, title: '衝浪', teacher: '戴貝羽', author: '賴品馨/六年級', tool: '彩畫/六角畫布', description: '這幅畫我參考葛飾北齋《神奈川衝浪》裏的海浪和富士山，想像自己在這幅畫的浪上開心衝浪。' },
    { id: 16, title: '藝同遊台北', teacher: '戴貝羽', author: '莊婕昀/六年級', tool: '設計/四開', description: '藝同遊台北這幅作品是使用手繪的方式呈現，畫中五張明信片的五個建築物是台北重要的藝術地標，各自分配在不同區域，標題的地方是使用禪繞畫的方式和一些簡單的色塊來做呈現，背景則是用藍曬圖的概念去做繪製。' },
  ],
  jaes: [
    { id: 1, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 2, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 3, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 4, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 5, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 6, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 7, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 8, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 9, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 10, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 11, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 12, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 13, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 14, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 15, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 16, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
  ],
  tyes: [
    { id: 1, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 2, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 3, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 4, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 5, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 6, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 7, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 8, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 9, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 10, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 11, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 12, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 13, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 14, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 15, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 16, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
  ],
  wjhs: [
    { id: 1, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 2, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 3, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 4, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 5, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 6, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 7, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 8, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 9, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 10, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 11, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 12, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 13, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 14, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 15, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
  ],
  ktjg: [
    { id: 1, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 2, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 3, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 4, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 5, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 6, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 7, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 8, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 9, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 10, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 11, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 12, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 13, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 14, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 15, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
  ],
  blsh: [
    { id: 1, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 2, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 3, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 4, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 5, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 6, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 7, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 8, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 9, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 10, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 11, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 12, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 13, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 14, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 15, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' }
  ],
  jjhs: [
    { id: 1, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 2, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 3, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 4, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 5, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 6, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 7, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 8, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 9, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 10, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 11, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 12, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 13, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 14, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 15, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
  ],
  zzsh: [
    { id: 1, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 2, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 3, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 4, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 5, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 6, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 7, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 8, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 9, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 10, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' }
  ],
  mlsh: [
    { id: 1, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 2, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 3, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 4, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 5, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 6, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 7, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 8, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 9, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 10, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' }
  ],
  fhsh: [
    { id: 1, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 2, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 3, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 4, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 5, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 6, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 7, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 8, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 9, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' },
    { id: 10, title: '作品名稱', teacher: '漢漢', author: '殘寶寶/三年級', tool: '水彩/四開', description: '眼睛花花腦袋開開，複製貼上作品說明心豪累' }
  ]
}
